spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: admin
    platform:
    driver-class-name: org.h2.Driver
    initialization-mode: always
